[package]
name = "tornado_common_logger"
version = "0.0.1"
authors = [
    "Francesco Cina <mr.francesco.cina@gmail.com>"
]
edition = "2018"

[dependencies]
chrono = "0.4"
fern = "0.6"
log = "0.4"
serde = { version = "1.0", features = ['derive'] }
thiserror = "1.0"
