[package]
name = "tornado_common_logger"
version = "0.0.1"
authors = [
    "Francesco Cina <mr.francesco.cina@gmail.com>"
]
edition = "2018"

[dependencies]
chrono = "0.4"
log = "0.4"
serde = { version = "1.0", features = ['derive'] }
thiserror = "1.0"
tracing = "0.1"
tracing-appender = "0.1"
tracing-futures = "0.2"
tracing-log = "0.1"
tracing-subscriber = "0.2"

[dev-dependencies]
tokio = { version = "0.2", features = ["macros", "rt-threaded"] }