[package]
name = "dto"
version = "0.0.1"
authors = [
    "Francesco Cina <mr.francesco.cina@gmail.com>"
]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tornado_common_api = { path = "../../common/api", version = "0.0.1" }
tornado_engine_matcher = { path = "../../engine/matcher", version = "0.0.1" }
typescript-definitions = "0.1"

[target.wasm32-unknown-unknown.dependencies]
wasm-bindgen = "0.2"
