[package]
name = "tornado_common_metrics"
version = "0.0.1"
authors = [
    "Francesco Cina <mr.francesco.cina@gmail.com>"
]
edition = "2018"

[dependencies]
actix-web = { version = "4.0.0-beta.9", optional = true }
log.workspace = true
opentelemetry = { version = "0.16", features = ["metrics", "rt-tokio"] }
opentelemetry-prometheus = "0.9"
prometheus = "0.12"

[dev-dependencies]
actix-rt = "2.2"
rand = "0.8"
tokio.workspace = true

[features]
default = []

actix_web = ["actix-web"]
