[package]
name = "dynamic_log"
version = "0.1.0"
authors = ["Francesco Cina <mr.francesco.cina@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1"
slog = "2"
slog-async = "2"
slog-atomic = "3"
slog-term = "2"