[package]
name = "tornado_common_parser"
version = "0.0.1"
authors = ["Francesco Cina <mr.francesco.cina@gmail.com>"]
edition = "2018"


[dependencies]
tornado_common_api = { path = "../api", version = "0.0.1" }
lazy_static = "1.4"
regex = { workspace = true }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
