[package]
name = "tornado_common_api"
version = "0.0.1"
authors = [
    "Benjamin Groeber <Benjamin.Groeber@wuerth-phoenix.com>",
    "Francesco Cina <mr.francesco.cina@gmail.com>"
]
edition = "2018"

[dependencies]
chrono = "0.4"
num-cmp = "0.1"
serde = "1.0"
serde_derive = "1.0"

[dev-dependencies]
serde_json = "1.0"