[package]
name = "tornado_common_api"
version = "0.0.1"
authors = [
    "Benjamin Groeber <Benjamin.Groeber@wuerth-phoenix.com>",
    "Francesco Cina <mr.francesco.cina@gmail.com>"
]

[dependencies]
chrono = "0.4"
serde = "1.0"
serde_derive = "1.0"
