[package]
name = "tornado_webhook_collector"
version = "0.0.1"
authors = ["Francesco Cina <mr.francesco.cina@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.9"
actix-web = "2"
chrono = "0.4"
clap = "2.33"
config_rs = { version = "0.9", package = "config" }
failure = "0.1"
failure_derive = "0.1"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tornado_common_api = { path = "../../common/api", version = "0.0.1" }
tornado_common_logger = { path = "../../common/logger", version = "0.0.1" }
tornado_collector_common = { path = "../../collector/common", version = "0.0.1" }
tornado_collector_jmespath = { path = "../../collector/jmespath", version = "0.0.1" }
tornado_common = { path = "../common", version = "0.0.1" }

[dev-dependencies]
