[package]
name = "tornado_webhook_collector"
version = "0.0.1"
authors = ["Francesco Cina <mr.francesco.cina@gmail.com>"]
edition = "2018"

[dependencies]
actix.workspace = true
actix-web.workspace = true
chrono.workspace = true
clap = { version = "3.0.0-beta.5", default-features = false, features = ["derive", "std"] }
config_rs = { version = "0.11", package = "config", default-features = false, features = ["toml"] }
human-units = { version = "0.5.1", features = ["serde"] }
log.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tornado_common_api = { path = "../../common/api", version = "0.0.1" }
tornado_common_logger = { path = "../../common/logger", version = "0.0.1" }
tornado_collector_common = { path = "../../collector/common", version = "0.0.1" }
tornado_collector_jmespath = { path = "../../collector/jmespath", version = "0.0.1" }
tornado_common = { path = "../common", version = "0.0.1", features = ["nats"] }
tracing-actix-web.workspace = true

[dev-dependencies]
actix-rt = "2.2"
