[package]
name = "spike_icinga2_api"
version = "0.0.1"
authors = ["Francesco Cina <mr.francesco.cina@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.7"
actix-web = { version = "0.7", features=["ssl"] }
base64 = "0.10"
futures = "0.1"
http = "0.1"
jmespath = "0.2"
openssl = "0.10"
reqwest = "0.9"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tornado_common_api = { path = "../../common/api", version = "0.0.1" }
tornado_common_logger = { path = "../../common/logger", version = "0.0.1" }
