[package]
name = "tornado_sms_collector"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "3.0.0-beta.5", default-features = false, features = ["derive", "std"] }
config_rs = { version = "0.11", package = "config", default-features = false, features = ["toml"] }
gethostname = "0.4"
log.workspace = true
serde.workspace = true
chrono = "0.4"
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing = "0.1"
tracing-futures = "0.2"
tracing-opentelemetry = "0.16.0"
opentelemetry = "0.16"
tornado_common_api = { path = "../../common/api", version = "0.0.1" }
tornado_common_logger = { path = "../../common/logger", version = "0.0.1" }
tornado_common = { path = "../common", version = "0.0.1", features = ["nats"] }
tornado_common_metrics = { path = "../../common/metrics", version = "0.0.1" }
