[package]
name = "tornado_engine_api_dto"
version = "0.0.1"
authors = [
    "Francesco Cina <mr.francesco.cina@gmail.com>"
]
edition = "2018"

[dependencies]
ajars = "0.6"
typescript-definitions = { package = "typescript-definitions-ufo-patch", version = "0.1.11" }

serde.workspace = true
serde_json.workspace = true

tornado_engine_matcher = { path = "../../engine/matcher", version = "0.0.1" }

[dev-dependencies]
