# The complete URL of the Icinga2 APIs
server_api_url = "https://localhost:5665/v1/actions"
# Username used to connect to the Icinga2 APIs
username = "root"
# Password used to connect to the Icinga2 APIs
password = ""
# If true, the client will not verify the SSL certificate
disable_ssl_verification = true
