[package]
name = "tornado_collector_common"
version = "0.0.1"
authors = [
    "Francesco Cina <mr.francesco.cina@gmail.com>"
]
edition = "2018"

[dependencies]
thiserror = "1.0"
tornado_common_api = { path = "../../common/api", version = "0.0.1" }
