[logger]

# The Logger level
# Valid values: trace, debug, info, warn, error
level = "debug"

# Whether the Logger should print to standard output.
# Valid values: true, false
stdout_output = true

# A file path in the file system; if provided, the Logger will append any output to it.
# file_output_path = "/output/file.log"


[rsyslog_collector]

# Set the size of the in-memory queue where messages will be stored before being written
# to the output socket.
message_queue_size = 10000

# The channel to send events to Tornado. Valid values are:
# - NatsStreaming
# - TCP
tornado_connection_channel = "TCP"

# The Tornado IP address where outgoing events will be written
tornado_event_socket_ip = "127.0.0.1"
# The Tornado port where outgoing events will be written
tornado_event_socket_port = 4747

# The addresses of the  NATS streaming server
nats.base.addresses = ["127.0.0.1:4222"]
# The NATS streaming Subject where tornado will subscribe and listen for incoming events
nats.base.subject = "tornado.events"
# The NATS streaming cluster id to connect to
nats.base.cluster_id = "test-cluster"
# The unique client id to connect to NATS streaming
nats.base.client_id = "tornado_webhook_collector_01"