[package]
name = "tornado_executor_icinga2"
version = "0.0.1"
authors = [
    "Francesco Cina <mr.francesco.cina@gmail.com>"
]
edition = "2018"

[dependencies]
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
tornado_executor_common = { path = "../common", version = "0.0.1" }
tornado_common_api = { path = "../../common/api", version = "0.0.1" }

[dev-dependencies]
maplit = "1.0"