[package]
name = "tornado_executor_icinga2"
version = "0.0.1"
authors = [
    "Francesco Cina <mr.francesco.cina@gmail.com>"
]
edition = "2018"

[dependencies]
async-trait = "0.1"
base64 = "0.13"
log = "0.4"
maplit = "1.0"
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls-native-roots"]}
serde = { version = "1.0", features = ['derive'] }
serde_json = "1"
tornado_executor_common = { path = "../common", version = "0.0.1" }
tornado_common_api = { path = "../../common/api", version = "0.0.1" }

[dev-dependencies]
actix-rt = "2.2"
actix-web = "4.0.0-beta.8"
httpmock = "0.5"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }