[package]
name = "tornado_engine_matcher"
version = "0.0.1"
authors = [
    "Francesco Cina <mr.francesco.cina@gmail.com>"
]

[dependencies]
failure = "0.1"
failure_derive = "0.1"
regex = "1"

[dev-dependencies]
