[package]
name = "tornado_nats_json_collector"
version = "0.0.1"
authors = ["Francesco Cina <mr.francesco.cina@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.12"
actix-rt = "2.2"
chrono = "0.4"
clap = "2.33"
config_rs = { version = "0.11", package = "config", default-features = false, features = ["toml"] }
log = "0.4"
serde = { version = "1.0", features = ['derive'] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1" }
tornado_common_api = { path = "../../common/api", version = "0.0.1" }
tornado_common_logger = { path = "../../common/logger", version = "0.0.1" }
tornado_collector_common = { path = "../../collector/common", version = "0.0.1" }
tornado_collector_jmespath = { path = "../../collector/jmespath", version = "0.0.1" }
tornado_common = { path = "../common", version = "0.0.1", features = ["nats"] }

[dev-dependencies]
maplit = "1.0"
rand = "0.8"
testcontainers = "0.12"
