[package]
name = "tornado_spike_stdin"
version = "0.0.1"
authors = [
    "Francesco Cina <mr.francesco.cina@gmail.com>"
]

[dependencies]
actix = "0.7"
futures = "0.1"
tokio = "0.1"
tokio-codec = "0.1"
tokio-io = "0.1"


[dev-dependencies]
