[package]
name = "tornado_spike_stdin"
version = "0.0.1"
authors = [
    "Francesco Cina <mr.francesco.cina@gmail.com>"
]

[dependencies]
actix = "0.7"
config = "0.9"
futures = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
structopt = "0.2"
tokio = "0.1"
tokio-codec = "0.1"
tokio-io = "0.1"


[dev-dependencies]
