[logger]

# The Logger level
# Valid values: trace, debug, info, warn, error
level = "debug"

# Whether the Logger should print to standard output.
# Valid values: true, false
stdout_output = true

# A file path in the file system; if provided, the Logger will append any output to it.
# file_output_path = "/output/file.log"


[email_collector]

# Set the size of the in-memory queue where messages will be stored before being written
# to the output socket.
message_queue_size = 10000

# The Unix Socket path where we will listen for incoming emails.
uds_path = "./target/tornado-email.sock"


[email_collector.tornado_connection_channel]

# In case of NatsStreaming Connection uncomment these entries; otherwise, comment them.
# -----------------------------------
# The addresses of the  NATS streaming server
#nats_streaming.base.addresses = ["127.0.0.1:4222"]
# The NATS streaming Subject where tornado will subscribe and listen for incoming events
#nats_streaming.base.subject = "tornado.events"
# The NATS streaming cluster id to connect to
#nats_streaming.base.cluster_id = "test-cluster"
# The unique client id to connect to NATS streaming
#nats_streaming.base.client_id = "tornado_email_collector_01"

# In case of TCP Connection uncomment these entries; otherwise, comment them.
# -----------------------------------
# The Tornado IP address where outgoing events will be written
tcp_socket_ip = "127.0.0.1"
# The Tornado port where outgoing events will be written
tcp_socket_port = 4747