# The complete URL of the Icinga2 Event Stream API
server_api_url = "https://127.0.0.1:5665/v1/events"
# Username used to connect to the Icinga2 APIs
username = "root"
# Password used to connect to the Icinga2 APIs
password = ""
# If true, the client will not verify the SSL certificate
disable_ssl_verification = true