[logger]

# The Logger level
# Valid values: trace, debug, info, warn, error
level = "trace"

# Whether the Logger should print to standard output.
# Valid values: true, false
stdout_output = true

# A file path in the file system; if provided, the Logger will append any output to it.
# file_output_path = "/output/file.log"

[tornado]

[tornado.daemon]
# The IP address where we will listen for incoming events.
event_socket_ip = "0.0.0.0"
#The port where we will listen for incoming events.
event_socket_port = 4747
# The IP address where the Tornado Web Server will listen for HTTP requests.
# This is used, for example, by the monitoring endpoints.
web_server_ip = "0.0.0.0"
# The port where the Tornado Web Server will listen for HTTP requests.
web_server_port = 4748
