[logger]

# The Logger level
# Valid values: trace, debug, info, warn, error
level = "debug"

# Whether the Logger should print to standard output.
# Valid values: true, false
stdout_output = true

# A file path in the file system; if provided, the Logger will append any output to it.
# file_output_path = "/output/file.log"


[icinga2_collector]

# Set the size of the in-memory queue where messages will be stored before being written
# to the output socket.
message_queue_size = 10000

[icinga2_collector.tornado_connection_channel]

# In case of Nats Connection uncomment these entries; otherwise, comment them.
# -----------------------------------
# The addresses of the  NATS server
#nats.client.addresses = ["127.0.0.1:4222"]
# The NATS Subject where tornado will subscribe and listen for incoming events
#nats.subject = "tornado.events"
# The type of authentication used when connecting to the NATS server
#nats.client.auth.type = "None"
#nats.client.auth.type = "Tls"
# The path to a pkcs12 bundle file which contains the certificate and private key to authenicate to the NATS server
#nats.client.auth.path_to_pkcs12_bundle = "/path/to/pkcs12/bundle.pfx"
# The password used to decrypt the pkcs12 bundle
#nats.client.auth.pkcs12_bundle_password = ""
# The path to a root certificate (in .pem format) to trust in addition to system's trust root.
# May be useful if the NATS server is not trusted by the system as default. Optional
#nats.client.auth.path_to_root_certificate = "/path/to/root/certificate.crt.pem"

# In case of TCP Connection uncomment these entries; otherwise, comment them.
# -----------------------------------
# The Tornado IP address where outgoing events will be written
tcp_socket_ip = "127.0.0.1"
# The Tornado port where outgoing events will be written
tcp_socket_port = 4747


[icinga2_collector.connection]

# The complete URL of the Icinga2 Event Stream API
server_api_url = "https://127.0.0.1:5665/v1/events"
# Username used to connect to the Icinga2 APIs
username = "root"
# Password used to connect to the Icinga2 APIs
password = ""
# If true, the client will not verify the SSL certificate
disable_ssl_verification = true
# In case of connection failure, the number of milliseconds to wait before a new connection attempt.
sleep_ms_between_connection_attempts = 5000