[package]
name = "tornado_engine_matcher"
version = "0.0.1"
authors = [
    "Francesco Cina <mr.francesco.cina@gmail.com>"
]
edition = "2018"

[dependencies]
chrono = "0.4.15"
fs_extra = "1.2"
lazy_static = "1.4"
log = "0.4"
regex = "1.3"
serde = { version = "1.0", features = ['derive'] }
serde_json = "1.0"
tempfile = "3"
thiserror = "1.0"
tornado_common_api = { path = "../../common/api", version = "0.0.1" }
tornado_common_parser = { path = "../../common/parser", version = "0.0.1" }
tornado_network_common = { path = "../../network/common", version = "0.0.1" }

[dev-dependencies]
chrono = "0.4"
criterion = "0.3"
maplit = "1.0"
tornado_common_logger = { path = "../../common/logger", version = "0.0.1" }
tornado_network_simple = { path = "../../network/simple", version = "0.0.1" }

[[bench]]
name = "matcher_bench"
harness = false