[package]
name = "tornado_engine_matcher"
version = "0.0.1"
authors = [
    "Francesco Cina <mr.francesco.cina@gmail.com>"
]
edition = "2018"

[dependencies]
async-trait = "0.1"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
fs_extra = "1.2"
lazy_static = "1.4"
log = "0.4"
regex = "1.5"
serde = { version = "1.0", features = ['derive'] }
serde_json = "1.0"
tempfile = "3"
thiserror = "1.0"
tokio = { version = "1", features = ["io-util", "fs", "rt"] }
tornado_common_api = { path = "../../common/api", version = "0.0.1" }
tornado_common_parser = { path = "../../common/parser", version = "0.0.1" }
tornado_network_common = { path = "../../network/common", version = "0.0.1" }
#typescript-definitions = "0.1.10"
typescript-definitions = { package = "typescript-definitions-ufo-patch", version = "0.1.11" }
tracing = "0.1"

etcd-client = "0.8.1"

[dev-dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock"] }
criterion = "0.3"
maplit = "1.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tornado_common_logger = { path = "../../common/logger", version = "0.0.1" }
tornado_network_simple = { path = "../../network/simple", version = "0.0.1" }

[[bench]]
name = "matcher_bench"
harness = false