[package]
name = "tornado_executor_common"
version = "0.0.1"
authors = [
    "Francesco Cina <mr.francesco.cina@gmail.com>"
]

[dependencies]
tornado_common_api = { path = "../../common/api", version = "0.0.1" }
