[package]
name = "tornado_engine_api"
version = "0.0.1"
authors = [
    "Francesco Cina <mr.francesco.cina@gmail.com>"
]
edition = "2018"

[dependencies]
actix = "0.9"
actix-web = "2"
async-trait = "0.1.24"
tornado_engine_api_dto = { path = "../engine_api_dto", version = "0.0.1" }
log = "0.4"
serde = { version = "1.0" }
serde_json = "1.0"
thiserror = "1.0"
tornado_common_api = { path = "../../common/api", version = "0.0.1" }
tornado_engine_matcher = { path = "../../engine/matcher", version = "0.0.1" }

[dev-dependencies]
actix-rt = "1.0.0"
