[package]
name = "tornado_engine_api"
version = "0.0.1"
authors = [
    "Francesco Cina <mr.francesco.cina@gmail.com>"
]
edition = "2018"

[dependencies]
actix = "0.12"
actix-web = "4.0.0-beta.9"
ajars = { version = "0.6", features = ["actix_web"] }
async-trait = "0.1"
base64.workspace = true
json-patch = "0.2"
log.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tornado_common_api = { path = "../../common/api", version = "0.0.1" }
tornado_engine_api_dto = { path = "../engine_api_dto", version = "0.0.1" }
tornado_engine_matcher = { path = "../../engine/matcher", version = "0.0.1" }

[dev-dependencies]
actix-rt = "2.2"
lazy_static = "1.4"
rand = "0.8"
tornado_common_logger = { path = "../../common/logger", version = "0.0.1" }
