[package]
name = "tornado_engine_api"
version = "0.0.1"
authors = [
    "Francesco Cina <mr.francesco.cina@gmail.com>"
]
edition = "2018"

[dependencies]
ajars = { version = "0.6", features = ["actix_web"] }
json-patch = "0.2"

actix.workspace = true
actix-web.workspace = true
async-trait.workspace = true
base64.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
gethostname = "0.4"
chrono = { default-features = false, features = ["clock"], workspace = true }

tornado_common_api = { path = "../../common/api", version = "0.0.1" }
tornado_engine_api_dto = { path = "../engine_api_dto", version = "0.0.1" }
tornado_engine_matcher = { path = "../../engine/matcher", version = "0.0.1" }

[dev-dependencies]
actix-rt = "2.2"
rand = "0.8"

lazy_static.workspace = true

tornado_common_logger = { path = "../../common/logger", version = "0.0.1" }
