[package]
name = "tornado_engine_api"
version = "0.0.1"
authors = [
    "Francesco Cina <mr.francesco.cina@gmail.com>"
]
edition = "2018"

[dependencies]
actix = "0.12"
actix-web = "4.0.0-beta.9"
ajars = { version = "0.6", features = ["actix_web"] }
async-trait = "0.1"
base64 = "0.13"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tornado_common_api = { path = "../../common/api", version = "0.0.1" }
tornado_engine_api_dto = { path = "../engine_api_dto", version = "0.0.1" }
tornado_engine_matcher = { path = "../../engine/matcher", version = "0.0.1" }

[dev-dependencies]
actix-rt = "2.2"
