[logger]
root_level = "warn"
output_system_enabled = true
output_file_enabled = false
output_file_name = ""

[logger.module_level]
tornado_engine_matcher = "info"
tornado_spike_tokio = "info"
tornado_executor_logger = "info"

[io]
json_rules_path = "./config/rules"
uds_socket_path = "/tmp/tornado_spike_tokio"