[package]
name = "tornado_engine"
version = "0.0.1"
authors = [
    "Francesco Cina <mr.francesco.cina@gmail.com>"
]
edition = "2018"

[dependencies]
actix = "0.11"
actix-cors = "0.6.0-beta.1"
actix-web = "=4.0.0-beta.5"
async-trait = "0.1"
chrono = "0.4"
clap = "2.33"
config_rs = { version = "0.11", package = "config", default-features = false, features = ["toml"] }
log = "0.4"
num_cpus = "1.13"
serde = { version = "1.0", features = ['derive'] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1", features = ["sync"] }
tornado_common = { path = "../common", version = "0.0.1", features = ["nats"] }
tornado_common_api = { path = "../../common/api", version = "0.0.1" }
tornado_common_logger = { path = "../../common/logger", version = "0.0.1" }
tornado_collector_common = { path = "../../collector/common", version = "0.0.1" }
tornado_collector_json = { path = "../../collector/json", version = "0.0.1" }
tornado_engine_api = { path = "../engine_api", version = "0.0.1" }
tornado_engine_api_dto = { path = "../engine_api_dto", version = "0.0.1" }
tornado_engine_matcher = { path = "../../engine/matcher", version = "0.0.1" }
tornado_executor_archive = { path = "../../executor/archive", version = "0.0.1" }
tornado_executor_common = { path = "../../executor/common", version = "0.0.1" }
tornado_executor_director = { path = "../../executor/director", version = "0.0.1" }
tornado_executor_elasticsearch = { path = "../../executor/elasticsearch", version = "0.0.1" }
tornado_executor_foreach = { path = "../../executor/foreach", version = "0.0.1" }
tornado_executor_icinga2 = { path = "../../executor/icinga2", version = "0.0.1" }
tornado_executor_logger = { path = "../../executor/logger", version = "0.0.1" }
tornado_executor_monitoring = { path = "../../executor/monitoring", version = "0.0.1" }
tornado_executor_script = { path = "../../executor/script", version = "0.0.1" }
tornado_executor_smart_monitoring_check_result = { path = "../../executor/smart_monitoring_check_result", version = "0.0.1" }
tornado_network_common = { path = "../../network/common", version = "0.0.1" }

[dev-dependencies]
actix-rt = "2.2"
chrono = "0.4"
lazy_static = "1.4"
fs_extra = "1.2"
maplit = "1.0"
tempfile = "3"
rand = "0.8"
tokio = { version = "1", features = ["macros", "sync", "rt-multi-thread"] }
tracing-subscriber = "0.2"
