[package]
name = "tornado_engine"
version = "0.0.1"
authors = [
    "Francesco Cina <mr.francesco.cina@gmail.com>"
]
edition = "2018"

[dependencies]
actix.workspace = true
actix-web.workspace = true
ajars = { version = "0.6", features = ["reqwest"] }
async-trait.workspace = true
base64.workspace = true
chrono.workspace = true
clap = { version = "3.0.0-beta.5", default-features = false, features = ["derive", "std"] }
config_rs = { version = "0.11", package = "config", default-features = false, features = ["toml"] }
log.workspace = true
num_cpus = "1.13"
regex = { workspace = true }
serde.workspace = true
serde_json.workspace = true
serde_regex = "1.1"
thiserror.workspace = true
tokio = { version = "1", features = ["sync"] }
tornado_common = { path = "../common", version = "0.0.1", features = ["nats"] }
tornado_common_api = { path = "../../common/api", version = "0.0.1" }
tornado_common_logger = { path = "../../common/logger", version = "0.0.1" }
tornado_common_metrics = { path = "../../common/metrics", version = "0.0.1", features = ["actix_web"] }
tornado_collector_common = { path = "../../collector/common", version = "0.0.1" }
tornado_collector_json = { path = "../../collector/json", version = "0.0.1" }
tornado_engine_api = { path = "../engine_api", version = "0.0.1" }
tornado_engine_api_dto = { path = "../engine_api_dto", version = "0.0.1" }
tornado_engine_matcher = { path = "../../engine/matcher", version = "0.0.1" }
tornado_executor_archive = { path = "../../executor/archive", version = "0.0.1" }
tornado_executor_common = { path = "../../executor/common", version = "0.0.1" }
tornado_executor_director = { path = "../../executor/director", version = "0.0.1" }
tornado_executor_elasticsearch = { path = "../../executor/elasticsearch", version = "0.0.1" }
tornado_executor_foreach = { path = "../../executor/foreach", version = "0.0.1" }
tornado_executor_icinga2 = { path = "../../executor/icinga2", version = "0.0.1" }
tornado_executor_logger = { path = "../../executor/logger", version = "0.0.1" }
tornado_executor_monitoring = { path = "../../executor/monitoring", version = "0.0.1" }
tornado_executor_script = { path = "../../executor/script", version = "0.0.1" }
tornado_executor_smart_monitoring_check_result = { path = "../../executor/smart_monitoring_check_result", version = "0.0.1" }
tornado_network_common = { path = "../../network/common", version = "0.0.1" }
tracing.workspace = true
tracing-actix-web.workspace = true
tracing-futures = "0.2"
tracing-opentelemetry = "0.16"

[dev-dependencies]
actix-rt = "2.2"
chrono.workspace = true
httpmock = "0.6"
lazy_static.workspace = true
fs_extra = "1.2"
maplit = "1.0"
tempfile = "3"
rand = "0.8"
tokio = { version = "1", features = ["macros", "sync", "rt-multi-thread"] }
tracing-subscriber = { version = "0.3", default-features = false }
