[package]
name = "tornado_engine"
version = "0.0.1"
authors = [
    "Francesco Cina <mr.francesco.cina@gmail.com>"
]
edition = "2018"

[dependencies]
actix = "0.9"
actix-cors = "0.2"
actix-rt = "1"
actix-web = { version = "2.0", features=["openssl"] }
async-trait = "0.1"
base64 = "0.11"
chrono = "0.4"
clap = "2.33"
config_rs = { version = "0.9", package = "config" }
http = "0.2"
log = "0.4"
num_cpus = "1.12"
openssl = "0.10"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
thiserror = "1.0"
tornado_common = { path = "../common", version = "0.0.1", features = ["nats_streaming"] }
tornado_common_api = { path = "../../common/api", version = "0.0.1" }
tornado_common_logger = { path = "../../common/logger", version = "0.0.1" }
tornado_collector_common = { path = "../../collector/common", version = "0.0.1" }
tornado_collector_json = { path = "../../collector/json", version = "0.0.1" }
tornado_engine_api = { path = "../engine_api", version = "0.0.1" }
tornado_engine_matcher = { path = "../../engine/matcher", version = "0.0.1" }
tornado_executor_archive = { path = "../../executor/archive", version = "0.0.1" }
tornado_executor_common = { path = "../../executor/common", version = "0.0.1" }
tornado_executor_elasticsearch = { path = "../../executor/elasticsearch", version = "0.0.1" }
tornado_executor_foreach = { path = "../../executor/foreach", version = "0.0.1" }
tornado_executor_icinga2 = { path = "../../executor/icinga2", version = "0.0.1" }
tornado_executor_logger = { path = "../../executor/logger", version = "0.0.1" }
tornado_executor_script = { path = "../../executor/script", version = "0.0.1" }
tornado_network_common = { path = "../../network/common", version = "0.0.1" }

[dev-dependencies]
lazy_static = "1.4"
maplit = "1.0"