[package]
name = "tornado_common_api"
version = "0.0.1"
authors = [
    "Benjamin Groeber <Benjamin.Groeber@wuerth-phoenix.com>",
    "Francesco Cina <mr.francesco.cina@gmail.com>"
]
edition = "2018"

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock"] }
num-cmp = "0.1"
serde = { version = "1.0", features = ['derive'] }
serde_json = "1"
uuid = { version = "0.8", default-features = false, features = ["v4"] }

[dev-dependencies]
