[logger]

# The Logger level
# Valid values: trace, debug, info, warn, error
level = "info"

# Whether the Logger should print to standard output.
# Valid values: true, false
stdout_output = true

# A file path in the file system; if provided, the Logger will append any output to it.
# file_output_path = "/output/file.log"

[logger.tracing_elastic_apm]
# Whether the Logger data should be sent to the Elastic APM Server.
# Valid values: true, false
apm_output = false
## The url of the Elastic APM server.
apm_server_url = "http://localhost:8200"
#apm_server_api_credentials.id = "api_id"
#apm_server_api_credentials.key = "api_key"

[sms_collector]

# The location where sms who could not be sent to tornado end up in.
failed_sms_folder = "/neteye/local/tornado_sms_collector/data/processing_failures_sms/"

# The channel to send events to Tornado.
# It contains the set of entries required to configure a Nats or a TCP connection.
[sms_collector.tornado_connection_channel]

# In case of Nats Connection uncomment these entries; otherwise, comment them.
# -----------------------------------
# The addresses of the  NATS server
nats.client.addresses = ["127.0.0.1:4222"]
# The NATS Subject to which tornado will subscribe to and listens for incoming events
nats.subject = "tornado.events"
# The type of authentication used when connecting to the NATS server
# (Optional. Valid values: None, Tls. Defaults to "None" if not provided).
nats.client.auth.type = "None"
#nats.client.auth.type = "Tls"
# The path to the client certificate (in .pem format) used to authenticate to the NATS server
#nats.client.auth.certificate_path = "/path/to/certificate.pem"
# The path to the client certificate private key (in .pem format) used to authenticate to the NATS server
#nats.client.auth.private_key_path = "/path/to/key.pem"
# The path to a root certificate (in .pem format) to trust in addition to system's trust root.
# May be useful if the NATS server is not trusted by the system as default.
# (Optional, valid if "nats.client.auth.type" is set to "Tls").
#nats.client.auth.path_to_root_certificate = "/path/to/root/certificate.crt.pem"
