[package]
name = "spike_uds_writer_collector"
version = "0.0.1"
authors = [
    "Francesco Cina <mr.francesco.cina@gmail.com>"
]

[dependencies]
config = "0.9"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tornado_common_api = { path = "../../common/api", version = "0.0.1" }
tornado_common_logger = { path = "../../common/logger", version = "0.0.1" }

[dev-dependencies]
