[workspace]

members = [
   "common/api",
   "common/logger",
   "collector/common",
   "collector/json",
   "engine/matcher",
   "executor/common",
   "network/common",
   "network/simple",
   "spike/actix",
   "spike/tokio",
]
