# Prerequisites:
# Install cargo-make:
# > cargo install --force cargo-make


# Starts the Tornado Engine.
#
# Execute with:
# > cargo make run-engine
[tasks.run-engine]
workspace = false
command = "cargo"
args = [
    "run",
    "--bin",
    "tornado_engine",
    "--",
    "--logger-stdout",
    "--logger-level=debug",
    "--uds-path=/tmp/tornado",
    "--config-dir=./tornado/engine/config",
    "--snmptrapd-uds-path=/tmp/tornado_snmptrapd"
]
dependencies = ["build"]


# Starts the rsyslog-collector and the spike_rsyslog_collector_writer.
#
# The spike_rsyslog_collector_writer will generate fake rsyslog events
# and will piped them into the rsyslog_collector.
# Consequently, the rsyslog_collector will process the events
# and send Tornado Events to the Engine.
#
# Execute with:
# > cargo make run-rsyslog-collector
[tasks.run-rsyslog-collector]
workspace = false
script = [
    "cargo run --bin spike_rsyslog_collector_writer -- --json-events-path=./spike/rsyslog_collector_writer/events |",
    "cargo run --bin tornado_rsyslog_collector -- --logger-stdout --logger-level=debug --uds-path=/tmp/tornado"
]
dependencies = ["build"]


# Starts the spike_snmptrapd_collector_writer.
#
# The spike_snmptrapd_collector_writer will generate fake snmptrapd
# events and forward them to the Engine UDS socket.
#
# Execute with:
# > cargo make run-snmptrapd-writer
[tasks.run-snmptrapd-writer]
workspace = false
command = "cargo"
args = [
    "run",
    "--bin",
    "spike_snmptrapd_collector_writer",
    "--",
    "--logger-stdout",
    "--logger-level=debug",
    "--json-events-path=./spike/snmptrapd_collector_writer/events",
    "--snmptrapd-uds-path=/tmp/tornado_snmptrapd"
]
dependencies = ["build"]


# Starts the tornado_icinga2_collector.
#
# Execute with:
# > cargo make run-icinga2-collector
[tasks.run-icinga2-collector]
workspace = false
command = "cargo"
args = [
    "run",
    "--bin",
    "tornado_icinga2_collector",
    "--",
    "--logger-stdout",
    "--logger-level=debug",
    "--uds-path=/tmp/tornado",
    "--config-dir=./tornado/icinga2_collector/config"
]
dependencies = ["build"]



# Starts the webhook-collector.
#
# Execute with:
# > cargo make run-webhook-collector
[tasks.run-webhook-collector]
workspace = false
command = "cargo"
args = [
    "run",
    "--bin",
    "tornado_webhook_collector",
    "--",
    "--logger-stdout",
    "--logger-level=debug",
    "--uds-path=/tmp/tornado",
    "--config-dir=./tornado/webhook_collector/config"
]
dependencies = ["build"]


# Starts a tornado events generator that sends simulated events to the Engine.
#
# Execute with:
# > cargo make run-tornado_events_generator
[tasks.run-tornado_events_generator]
workspace = false
command = "cargo"
args = [
    "run",
    "--bin",
    "spike_tornado_events_generator",
    "--",
    "--logger-stdout",
    "--logger-level=debug",
    "--uds-path=/tmp/tornado",
    "--config-dir=./spike/tornado_events_generator/config"
]
dependencies = ["build"]