# Prerequisites:
# Install cargo-make:
# > cargo install --force cargo-make


# Starts the Tornado Engine.
#
# Execute with:
# > cargo make run-engine
[tasks.run-engine]
workspace = false
command = "cargo"
args = [
    "run",
    "--bin",
    "tornado_engine",
    "--",
    "--logger-stdout",
    "--logger-level=debug",
    "--config-dir=./tornado/engine/config",
    "daemon",
    "--event-socket-ip=0.0.0.0",
    "--web-server-ip=0.0.0.0",
]


# Starts the rsyslog-collector and the spike_rsyslog_collector_writer.
#
# The spike_rsyslog_collector_writer will generate fake rsyslog events
# and will pipe them to the rsyslog_collector.
# Consequently, the rsyslog_collector will process the Events
# and send Tornado Events to the Engine.
#
# Execute with:
# > cargo make run-rsyslog-collector
[tasks.run-rsyslog-collector]
workspace = false
script = [
    "cargo run --bin spike_rsyslog_collector_writer -- --json-events-path=./spike/rsyslog_collector_writer/events |",
    "cargo run --bin tornado_rsyslog_collector -- --config-dir=./tornado/rsyslog_collector/config"
]


# Starts the tornado_icinga2_collector.
#
# Execute with:
# > cargo make run-icinga2-collector
[tasks.run-icinga2-collector]
workspace = false
command = "cargo"
args = [
    "run",
    "--bin",
    "tornado_icinga2_collector",
    "--",
    "--config-dir=./tornado/icinga2_collector/config"
]



# Starts the webhook-collector.
#
# Execute with:
# > cargo make run-webhook-collector
[tasks.run-webhook-collector]
workspace = false
command = "cargo"
args = [
    "run",
    "--bin",
    "tornado_webhook_collector",
    "--",
    "--logger-stdout",
    "--logger-level=debug",
    "--config-dir=./tornado/webhook_collector/config"
]


# Starts a Tornado Events generator that sends simulated Events to the Engine.
#
# Execute with:
# > cargo make run-tornado_events_generator
[tasks.run-tornado_events_generator]
workspace = false
command = "cargo"
args = [
    "run",
    "--bin",
    "spike_tornado_events_generator",
    "--",
    "--logger-stdout",
    "--logger-level=debug",
    "--config-dir=./spike/tornado_events_generator/config"
]


# Starts the tornado_email_collector.
#
# Execute with:
# > cargo make run-email-collector
[tasks.run-email-collector]
workspace = false
command = "cargo"
args = [
    "run",
    "--bin",
    "tornado_email_collector",
    "--",
    "--config-dir=./tornado/email_collector/config"
]
