[package]
name = "tornado_common"
version = "0.0.1"
authors = ["Francesco Cina <mr.francesco.cina@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.7"
failure = "0.1"
failure_derive = "0.1"
futures = "0.1"
log = "0.4"
serde_json = "1.0"
tokio = "0.1"
tokio-codec = "0.1"
tokio-io = "0.1"
tokio-tcp = "0.1"
tornado_common_api = { path = "../../common/api", version = "0.0.1" }


[target.'cfg(unix)'.dependencies]
tokio-uds = "0.2"
