[logger]
root_level = "error"
output_system_enabled = false
output_file_enabled = false
output_file_name = ""

[logger.module_level]

[io]
json_events_path = "./config/events"
repeat_send = 1000
repeat_sleep_ms = 1000