[package]
name = "tornado_webhook_collector"
version = "0.0.1"
authors = ["Francesco Cina <mr.francesco.cina@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.7"
actix-web = "0.7"
chrono = "0.4"
failure = "0.1"
failure_derive = "0.1"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
structopt = "0.2"
tokio = "0.1"
tokio-codec = "0.1"
tokio-io = "0.1"
tokio-uds = "0.2"
tornado_common_api = { path = "../../common/api", version = "0.0.1" }
tornado_common_logger = { path = "../../common/logger", version = "0.0.1" }
tornado_collector_common = { path = "../../collector/common", version = "0.0.1" }
tornado_collector_jmespath = { path = "../../collector/jmespath", version = "0.0.1" }


