[package]
name = "tornado_rsyslog_collector"
version = "0.0.1"
authors = [
    "Francesco Cina <mr.francesco.cina@gmail.com>"
]
edition = "2018"

[dependencies]
actix = "0.11"
actix-rt = "2.2"
clap = "2.33"
config_rs = { version = "0.11", package = "config" }
log = "0.4"
serde = { version = "1.0", features = ['derive'] }
serde_json = "1.0"
thiserror = "1.0"
tokio = "1"
tornado_common_api = { path = "../../common/api", version = "0.0.1" }
tornado_common_logger = { path = "../../common/logger", version = "0.0.1" }
tornado_collector_common = { path = "../../collector/common", version = "0.0.1" }
tornado_collector_json = { path = "../../collector/json", version = "0.0.1" }
tornado_common = { path = "../common", version = "0.0.1", features = ["nats"] }

[dev-dependencies]
