[package]
name = "tornado_common"
version = "0.0.1"
authors = ["Francesco Cina <mr.francesco.cina@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.9"
futures = "0.3.1"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "0.2", features = ["io-std", "io-util", "fs", "net", "time"] }
tokio-util = { version = "0.2", features = ["codec"] }
tornado_collector_common = { path = "../../collector/common", version = "0.0.1" }
tornado_collector_json = { path = "../../collector/json", version = "0.0.1" }
tornado_common_api = { path = "../../common/api", version = "0.0.1" }

# Feature nats
rants = { version = "0.4", optional = true }

[dev-dependencies]
actix-rt = "1"
port_check = "0.1.3"
rand = "0.7"
#testcontainers = "0.8.1"
testcontainers = { git = "https://github.com/ufoscout/testcontainers-rs.git", branch = "custom_run_options" }
tornado_common_logger = { path = "../../common/logger", version = "0.0.1" }

[features]
default = []

nats = ["rants"]