[package]
name = "tornado_common"
version = "0.0.1"
authors = ["Francesco Cina <mr.francesco.cina@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.10"
async-channel = "1.5.1"
async-trait = "0.1.40"
futures = "0.3.7"
log = "0.4"
serde = { version = "1.0", features = ['derive'] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "0.2", features = ["io-std", "io-util", "fs", "net", "time"] }
tokio-util = { version = "0.3", features = ["codec"] }
tornado_collector_common = { path = "../../collector/common", version = "0.0.1" }
tornado_collector_json = { path = "../../collector/json", version = "0.0.1" }
tornado_common_api = { path = "../../common/api", version = "0.0.1" }
tornado_executor_common = { path = "../../executor/common", version = "0.0.1" }

# Feature nats
rants = { version = "0.5", features = ["native-tls"], optional = true }

[dev-dependencies]
actix-rt = "1.1.1"
port_check = "0.1.3"
rand = "0.7"
serial_test = "*"
testcontainers = "0.11"
tornado_common_logger = { path = "../../common/logger", version = "0.0.1" }

[features]
default = []

nats = ["rants"]
nats_integration_tests = ["nats"]