[package]
name = "tornado_common"
version = "0.0.1"
authors = ["Francesco Cina <mr.francesco.cina@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.11"
async-channel = "1.6"
async-trait = "0.1"
futures-util = { version = "0.3", default-features = false, features=["std"]}
log = "0.4"
serde = { version = "1.0", features = ['derive'] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1", features = ["net", "time"] }
tokio-stream = { version = "0.1", features = ["net"] }
tokio-util = { version = "0.6", features = ["codec"] }
tornado_collector_common = { path = "../../collector/common", version = "0.0.1" }
tornado_collector_json = { path = "../../collector/json", version = "0.0.1" }
tornado_common_api = { path = "../../common/api", version = "0.0.1" }
tornado_executor_common = { path = "../../executor/common", version = "0.0.1" }

# BEGIN - REMOVE THIS ENTIRE BLOCK OF DEPS AS PART OF TOR-323 IMPLEMENTATION
actix-files = "0.6.0-beta.4"
actix-http = "=3.0.0-beta.5"
actix-rt = "2.2.0"
actix-service = "=2.0.0-beta.5"
actix-web = "=4.0.0-beta.5"
# END - REMOVE THIS ENTIRE BLOCK OF DEPS AS PART OF TOR-323 IMPLEMENTATION

# Feature nats
# Use WP fork which fixes the bug https://github.com/nats-io/nats.rs/issues/182
# see also https://siwuerthphoenix.atlassian.net/browse/TOR-326
# We can use the official version once the bug is fixed
async-nats = { git = "https://github.com/WuerthPhoenix/nats.rs", package = "async-nats", branch = "bugfix/messages-lost-by-publish-after-disconnection", optional = true }
#async-nats = { version = "0.9", optional = true }

[dev-dependencies]
actix-rt = "2.2"
chrono = "0.4"
port_check = "0.1"
rand = "0.8"
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls"] }
serial_test = "*"
testcontainers = "0.12"
tornado_common_logger = { path = "../../common/logger", version = "0.0.1" }

[features]
default = []

nats = ["async-nats"]
nats_integration_tests = ["nats"]